/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import Character_Classes.PlayableChar;
import Dungeon_Classes.Dungeon;
import Item_Classes.Item;
import game.GameGUI;
import javax.swing.DefaultListModel;

/**
 *
 * @author rhian
 */
public class GameMenuPanel extends javax.swing.JPanel {

    private MainFrame frame;

    /**
     * Creates new form GameMenuPanel
     */
    public GameMenuPanel(MainFrame frame) {
        initComponents();
        this.frame = frame;
        btnInventory.addActionListener(this::btnInventoryActionPerformed);
        btnQuit.addActionListener(this::btnQuitActionPerformed);
    }

    public void refresh() {
        
        PlayableChar yohane = GameGUI.getYohane();

         lblHP.setText(String.format("HP: %.1f / %.1f", yohane.getHealth(), yohane.getMaxHealth()));
        lblGold.setText("Gold: " + yohane.getGoldOwned());
        
        Item curItem = yohane.getCurItem();
        if (curItem != null) {
            int qty = java.util.Collections.frequency(yohane.getInventory(), curItem);
            String text = "Item on hand: " + curItem.getName();
            if (qty > 1) {
                text += " (" + qty + ")";
            }
            lblItem.setText(text);
        } else {
            lblItem.setText("Item on hand: N/A");
        }
        
        DefaultListModel<String> model = new DefaultListModel<>();
        
        Dungeon[] dungeons = GameGUI.getDungeons();

        if (GameGUI.isBossUnlocked()) {
            // All 3 dungeons cleared - the only choice left is the final dungeon.
            model.addElement("Face the " + dungeons[dungeons.length - 1].getName());
        } else {
            // dungeons[dungeons.length - 1] is the final/boss dungeon - don't
            // list it until it's actually unlocked.
            for (int i = 0; i < dungeons.length - 1; i++) {
                Dungeon d = dungeons[i];
                String label = d.isCompleted(yohane)
                        ? "[Cleared] " + d.getName()
                        : d.getName();
                model.addElement(label);
            }
        }

        lstDungeons.setModel(model);

        btnShop.setEnabled(GameGUI.isShopUnlocked());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblGold = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstDungeons = new javax.swing.JList<>();
        btnEnter = new javax.swing.JButton();
        btnShop = new javax.swing.JButton();
        btnInventory = new javax.swing.JButton();
        btnQuit = new javax.swing.JButton();
        lblItem = new javax.swing.JLabel();
        lblHP = new javax.swing.JLabel();

        lblGold.setText("jLabel1");

        lblTitle.setText("Choose a Dungeon");

        lstDungeons.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lstDungeons);

        btnEnter.setText("Enter Dungeon");
        btnEnter.addActionListener(this::btnEnterActionPerformed);

        btnShop.setText("Shop");

        btnInventory.setText("Inventory");
        btnInventory.addActionListener(this::btnInventoryActionPerformed);

        btnQuit.setText("Save and Quit");
        btnQuit.addActionListener(this::btnQuitActionPerformed);

        lblItem.setText("jLabel1");

        lblHP.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitle)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1)
                                .addComponent(btnEnter)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnShop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnInventory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnQuit, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(144, 144, 144))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblGold)
                        .addGap(45, 45, 45)
                        .addComponent(lblItem)
                        .addGap(55, 55, 55)
                        .addComponent(lblHP)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGold)
                    .addComponent(lblItem)
                    .addComponent(lblHP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnInventory)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnShop)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnQuit))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEnter)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterActionPerformed
        int index = lstDungeons.getSelectedIndex();

        if (index == -1)
            return;

        Dungeon[] dungeons = GameGUI.getDungeons();
        Dungeon chosen;

        if (GameGUI.isBossUnlocked()) {
            // Only one entry is ever shown in this state: the final dungeon.
            chosen = dungeons[dungeons.length - 1];
        } else {
            chosen = dungeons[index];
            if (chosen.isCompleted(GameGUI.getYohane())) {
                return; // already cleared - ignore the click
            }
        }

        GameGUI.startDungeon(chosen);

        frame.getGamePanel().refreshStats();
        frame.getGamePanel().refreshMap();

        frame.showCard("GAME");
    }//GEN-LAST:event_btnEnterActionPerformed

    private void btnInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventoryActionPerformed
        frame.getInventoryPanel().refresh();
        frame.showCard("INVENTORY");
    }//GEN-LAST:event_btnInventoryActionPerformed

    private void btnQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitActionPerformed
        frame.showCard("MENU");
    }//GEN-LAST:event_btnQuitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnter;
    private javax.swing.JButton btnInventory;
    private javax.swing.JButton btnQuit;
    private javax.swing.JButton btnShop;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblGold;
    private javax.swing.JLabel lblHP;
    private javax.swing.JLabel lblItem;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JList<String> lstDungeons;
    // End of variables declaration//GEN-END:variables
}
