/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import Character_Classes.PlayableChar;
import Dungeon_Classes.Dungeon;
import game.GameGUI;
import javax.swing.DefaultListModel;

/**
 *
 * @author rhian
 */
public class GameMenuPanel extends javax.swing.JPanel {

    private MainFrame frame;

    /**
     * Creates new form GameMenuPanel
     */
    public GameMenuPanel(MainFrame frame) {
        initComponents();
        this.frame = frame;
        btnInventory.addActionListener(this::btnInventoryActionPerformed);
        btnQuit.addActionListener(this::btnQuitActionPerformed);
    }

    public void refresh() {

        lblGold.setText("Gold: " + GameGUI.getYohane().getGoldOwned());

        DefaultListModel<String> model = new DefaultListModel<>();
        
        Dungeon[] dungeons = GameGUI.getDungeons();
        PlayableChar yohane = GameGUI.getYohane();

        if (GameGUI.isBossUnlocked()) {
            // All 3 dungeons cleared - the only choice left is the final dungeon.
            model.addElement("Face the " + dungeons[dungeons.length - 1].getName());
        } else {
            // dungeons[dungeons.length - 1] is the final/boss dungeon - don't
            // list it until it's actually unlocked.
            for (int i = 0; i < dungeons.length - 1; i++) {
                Dungeon d = dungeons[i];
                String label = d.isCompleted(yohane)
                        ? "[Cleared] " + d.getName()
                        : d.getName();
                model.addElement(label);
            }
        }

        lstDungeons.setModel(model);

        btnShop.setEnabled(GameGUI.isShopUnlocked());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblGold = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstDungeons = new javax.swing.JList<>();
        btnEnter = new javax.swing.JButton();
        btnShop = new javax.swing.JButton();
        btnInventory = new javax.swing.JButton();
        btnIdols = new javax.swing.JButton();
        btnQuit = new javax.swing.JButton();

        lblGold.setText("jLabel1");

        lblTitle.setText("Choose a Dungeon");

        lstDungeons.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lstDungeons);

        btnEnter.setText("Enter Dungeon");
        btnEnter.addActionListener(this::btnEnterActionPerformed);

        btnShop.setText("Shop");

        btnInventory.setText("Inventory");
        btnInventory.addActionListener(this::btnInventoryActionPerformed);

        btnIdols.setText("Idols");

        btnQuit.setText("Quit");
        btnQuit.addActionListener(this::btnQuitActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEnter)
                            .addComponent(btnShop)
                            .addComponent(btnIdols)
                            .addComponent(btnInventory)
                            .addComponent(btnQuit)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblTitle)
                        .addComponent(lblGold)))
                .addContainerGap(175, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblGold)
                .addGap(18, 18, 18)
                .addComponent(lblTitle)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(btnEnter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnShop)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnInventory)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnIdols)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnQuit)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterActionPerformed
        int index = lstDungeons.getSelectedIndex();

        if (index == -1)
            return;

        Dungeon[] dungeons = GameGUI.getDungeons();
        Dungeon chosen;

        if (GameGUI.isBossUnlocked()) {
            // Only one entry is ever shown in this state: the final dungeon.
            chosen = dungeons[dungeons.length - 1];
        } else {
            chosen = dungeons[index];
            if (chosen.isCompleted(GameGUI.getYohane())) {
                return; // already cleared - ignore the click
            }
        }

        GameGUI.startDungeon(chosen);

        frame.getGamePanel().refreshStats();
        frame.getGamePanel().refreshMap();

        frame.showCard("GAME");
    }//GEN-LAST:event_btnEnterActionPerformed

    private void btnInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventoryActionPerformed
        frame.getInventoryPanel().refresh();
        frame.showCard("INVENTORY");
    }//GEN-LAST:event_btnInventoryActionPerformed

    private void btnQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitActionPerformed
        frame.showCard("MENU");
    }//GEN-LAST:event_btnQuitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnter;
    private javax.swing.JButton btnIdols;
    private javax.swing.JButton btnInventory;
    private javax.swing.JButton btnQuit;
    private javax.swing.JButton btnShop;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblGold;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JList<String> lstDungeons;
    // End of variables declaration//GEN-END:variables
}
