/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import game.GameGUI;
import java.awt.CardLayout;
/**
 *
 * @author rhian
 */
public class MainFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());
    private MainMenuPanel menuPanel;
    private GameMenuPanel gameMenuPanel;
    private GamePanel gamePanel;
    private InventoryPanel inventoryPanel;
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        
        getContentPane().setLayout(new java.awt.BorderLayout());
        getContentPane().add(cardPanel, java.awt.BorderLayout.CENTER);
        
        menuPanel = new MainMenuPanel(this);
        gameMenuPanel = new GameMenuPanel(this);
        gamePanel = new GamePanel(this);
        inventoryPanel = new InventoryPanel(this);

        cardPanel.add(menuPanel, "MENU");
        cardPanel.add(gameMenuPanel, "GAMEMENU");
        cardPanel.add(gamePanel, "GAME");
        cardPanel.add(inventoryPanel, "INVENTORY");

        showCard("MENU");
    }
    
    public void showCard(String cardName) {
        if (cardName.equals("MENU")) {
            menuPanel.refresh();
        }
        CardLayout layout = (CardLayout) cardPanel.getLayout();
        layout.show(cardPanel, cardName);
    }
    
    public void startGame() {

        GameGUI.initialize();

        gamePanel.refreshStats();
        gamePanel.refreshMap();

        showCard("GAME");
    }
    
    public GamePanel getGamePanel() {
        return gamePanel;
    }

    public GameMenuPanel getGameMenuPanel() {
        return gameMenuPanel;
    }

    public MainMenuPanel getMainMenuPanel() {
        return menuPanel;
    }
    
    public InventoryPanel getInventoryPanel() {
        return inventoryPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cardPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1060, 460));
        setPreferredSize(new java.awt.Dimension(1060, 460));
        setResizable(false);

        cardPanel.setMinimumSize(new java.awt.Dimension(1060, 460));
        cardPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 323, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            MainFrame frame = new MainFrame();
            frame.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cardPanel;
    // End of variables declaration//GEN-END:variables
}
