/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.GameGUI;
import java.awt.CardLayout;
/**
 * Top-level Swing window and entry point of the View layer. Hosts every
 * game screen as a card in a {@link java.awt.CardLayout}, owns one
 * instance of each panel, and switches between them via {@link #showCard}.
 * Panels reach each other through this frame for cross-panel navigation
 * and refresh calls.
 * 
 * @author Katigbak and Porciuncula
 * @version 2.0
 */
public class MainFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());
    private MainMenuPanel menuPanel;
    private GameMenuPanel gameMenuPanel;
    private GamePanel gamePanel;
    private InventoryPanel inventoryPanel;
    private StatusPanel statusPanel;
    private ShopPanel shopPanel;
    
    /**
     * Constructs the main window, builds and registers every screen as a
     * card, and shows the main menu first.
     */
    public MainFrame() {
        initComponents();
        
        getContentPane().setLayout(new java.awt.BorderLayout());
        getContentPane().add(cardPanel, java.awt.BorderLayout.CENTER);
        
        menuPanel = new MainMenuPanel(this);
        gameMenuPanel = new GameMenuPanel(this);
        gamePanel = new GamePanel(this);
        inventoryPanel = new InventoryPanel(this);
        statusPanel = new StatusPanel(this);
        shopPanel = new ShopPanel(this);

        cardPanel.add(menuPanel, "MENU");
        cardPanel.add(gameMenuPanel, "GAMEMENU");
        cardPanel.add(gamePanel, "GAME");
        cardPanel.add(inventoryPanel, "INVENTORY");
        cardPanel.add(statusPanel, "STATUS");
        cardPanel.add(shopPanel, "SHOP");

        showCard("MENU");
    }
    
    /**
     * Switches the visible card to the one registered under the given
     * name, refreshing the main menu first if that's the card being shown.
     *
     * @param cardName the registered card identifier - one of
     *                 {@code "MENU"}, {@code "GAMEMENU"}, {@code "GAME"},
     *                 or {@code "INVENTORY"}
     */
    public void showCard(String cardName) {
        if (cardName.equals("MENU")) {
            menuPanel.refresh();
        }
        CardLayout layout = (CardLayout) cardPanel.getLayout();
        layout.show(cardPanel, cardName);
    }
    
    /**
     * Starts a fresh run: resets Controller state, refreshes the game
     * panel's stats and map, then switches to the game card.
     */
    public void startGame() {

        GameGUI.initialize();

        gamePanel.refreshStats();
        gamePanel.refreshMap();

        showCard("GAME");
    }
    
    /**
     * @return the game panel instance
     */
    public GamePanel getGamePanel() {
        return gamePanel;
    }
    
    /**
     * @return the dungeon-select menu panel instance
     */
    public GameMenuPanel getGameMenuPanel() {
        return gameMenuPanel;
    }
    
    /**
     * @return the main menu panel instance
     */
    public MainMenuPanel getMainMenuPanel() {
        return menuPanel;
    }

    /**
     * @return the inventory panel instance
     */ 
    public InventoryPanel getInventoryPanel() {
        return inventoryPanel;
    }

    /**
     * @return the shop panel instance
     */ 
    public ShopPanel getShopPanel() {
        return shopPanel;
    }
    
    /**
     * @return the status panel instance
     */ 
    public StatusPanel getStatusPanel() {
        return statusPanel;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cardPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1060, 460));
        setResizable(false);

        cardPanel.setMinimumSize(new java.awt.Dimension(1060, 460));
        cardPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 323, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Application entry point: applies the Nimbus look and feel if
     * available, then constructs and shows the main window.
     *
     * @param args command line arguments (unused)
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            MainFrame frame = new MainFrame();
            frame.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cardPanel;
    // End of variables declaration//GEN-END:variables
}
