/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;
import Controller.GameGUI;
/**
 * View panel for the game's main menu: lets the player start a new run,
 * continue one in progress, or quit. Button visibility and labeling
 * reflect the Controller's current run state.
 * 
 * @author Katigbak and Porciuncula
 * @version 2.0
 */
public class MainMenuPanel extends javax.swing.JPanel {

    private MainFrame frame;
    
    /**
     * Constructs the main menu panel and applies the shared UI theme.
     *
     * @param frame the main application frame, used for card navigation
     */
    public MainMenuPanel(MainFrame frame) {
        initComponents();
        UITheme.apply(this);
        this.frame = frame;
    }
    
    /**
     * Shows/hides Continue depending on whether a run is in progress, and
     * swaps the New Game button's label to "New Game+" once the player has
     * ever completed a run or hit a game over. Call this every time before
     * this panel is shown (MainFrame.showCard("MENU") already does this).
     */
    public void refresh() {
        btnContinue.setVisible(GameGUI.isOngoingGame());
        btnNewGame.setText(GameGUI.hasPriorRun() ? "New Game+" : "New Game");
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnNewGame = new javax.swing.JButton();
        btnContinue = new javax.swing.JButton();
        btnStatus = new javax.swing.JButton();
        btnQuit = new javax.swing.JButton();

        lblTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/title.png"))); // NOI18N

        btnNewGame.setText("New Game");
        btnNewGame.setMaximumSize(null);
        btnNewGame.setMinimumSize(new java.awt.Dimension(80, 25));
        btnNewGame.setPreferredSize(new java.awt.Dimension(140, 30));
        btnNewGame.addActionListener(this::btnNewGameActionPerformed);

        btnContinue.setText("Continue");
        btnContinue.setMaximumSize(null);
        btnContinue.setMinimumSize(new java.awt.Dimension(80, 25));
        btnContinue.setPreferredSize(new java.awt.Dimension(140, 30));
        btnContinue.addActionListener(this::btnContinueActionPerformed);

        btnStatus.setText("Status");
        btnStatus.setMaximumSize(null);
        btnStatus.setMinimumSize(new java.awt.Dimension(80, 25));
        btnStatus.setPreferredSize(new java.awt.Dimension(140, 30));
        btnStatus.addActionListener(this::btnStatusActionPerformed);

        btnQuit.setText("Quit");
        btnQuit.setMaximumSize(null);
        btnQuit.setMinimumSize(new java.awt.Dimension(80, 25));
        btnQuit.setPreferredSize(new java.awt.Dimension(140, 30));
        btnQuit.addActionListener(this::btnQuitActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnQuit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNewGame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnContinue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTitle))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTitle)
                .addGap(20, 20, 20)
                .addComponent(btnContinue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNewGame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnQuit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Handles the "Continue" button: refreshes and shows the dungeon-select menu.
     *
     * @param evt the button click event
     */
    private void btnContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinueActionPerformed
        frame.getGameMenuPanel().refresh();
        frame.showCard("GAMEMENU");
    }//GEN-LAST:event_btnContinueActionPerformed

    /**
     * Handles the "Status" button. Not yet implemented.
     *
     * @param evt the button click event
     */   
    private void btnStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnStatusActionPerformed

    /**
     * Handles the "New Game" / "New Game+" button: starts a new run via
     * the Controller, refreshes the dungeon-select menu, and shows it.
     *
     * @param evt the button click event
     */   
    private void btnNewGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewGameActionPerformed
        GameGUI.beginNewRun();

        frame.getGameMenuPanel().refresh();

        frame.showCard("GAMEMENU");
    }//GEN-LAST:event_btnNewGameActionPerformed

    /**
     * Handles the "Quit" button: exits the application immediately.
     *
     * @param evt the button click event
     */
    private void btnQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnQuitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinue;
    private javax.swing.JButton btnNewGame;
    private javax.swing.JButton btnQuit;
    private javax.swing.JButton btnStatus;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables

}
